services:
  - type: web
    name: seis-backend
    env: python
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    healthCheckPath: /students # Using a basic GET route to check health
    envVars:
      - key: DATABASE_URL
        sync: false
        # Needs to be set manually in Render's dashboard for your Supabase Postgres URL
      - key: PORT
        value: 10000
